export enum BandSyncMutationTypes {
    RESET = "BAND_SYNC_RESET",
    SET_ACTIVE = "BAND_SYNC_SET_ACTIVE",
    SET_SESSION = "BAND_SYNC_SET_SESSION",
    SET_PROCESSING = "BAND_SYNC_SET_PROCESSING",
    SET_ERROR = "BAND_SYNC_SET_ERROR",
    SET_SYNC_STATUS = "BAND_SYNC_SET_SYNC_STATUS",
    SET_FOLLOWING_LEADER_UPDATES = "BAND_SYNC_SET_FOLLOWING_LEADER_UPDATES",
}
